baseURL = 'https://obifarin.github.io/'
languageCode = 'en-us'
title = 'Academic Webpage'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Olatomiwa O. Bifarin"
description = "AI for Science | Machine Learning & Metabolomics | Postdoctoral Research Fellow at Georgia Tech"
keywords = ["Olatomiwa Bifarin", "Machine Learning", "AI", "Metabolomics", "Biochemistry", "Research", "Georgia Tech"]
author = " "
# images = ["<link or path of image for opengraph, twitter-cards>"]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.homeInfoParams]
Title = ""
Content = """

"""


[params.assets]
# disableHLJS = true
# disableFingerprinting = true
favicon = "<link / abs url>"
favicon16x16 = "<link / abs url>"
favicon32x32 = "<link / abs url>"
apple_touch_icon = "<link / abs url>"
safari_pinned_tab = "<link / abs url>"

# Custom styling
[params.profileMode]
enabled = false

# Force custom CSS to be included
[params.customCSS]
enabled = true

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = true

#[params.editPost]
#URL = "https://github.com/<path_to_repo>/content"
#Text = "Suggest Changes"
#appendFilePath = true

# Social media icons (commented out - using custom implementation)
# [[params.socialIcons]]
# name = "github"
# url = "https://github.com/obifarin"
# 
# [[params.socialIcons]]
# name = "linkedin"
# url = "https://www.linkedin.com/in/obifarin/"
# 
# [[params.socialIcons]]
# name = "scholar"
# url = "https://scholar.google.com/citations?user=rx9OI0MAAAAJ&hl=en"
# 
# [[params.socialIcons]]
# name = "twitter"
# url = "https://twitter.com/obifarin"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 10

[[menu.main]]
identifier = "news"
name = "news"
url = "/news/"
weight = 20

[[menu.main]]
identifier = "publications"
name = "publications"
url = "/publications/"
weight = 30

[[menu.main]]
identifier = "cv"
name = "cv"
url = "https://drive.google.com/file/d/19VbbT_tNRkKyz4sgNSMkAorbViDQ7A5m/view?usp=sharing"
weight = 40

[[menu.main]]
  identifier = "ai-blog"
  name = "ai blog"
  url = "https://theepsilon.substack.com/"
  weight = 50

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "github"
